### ISSUE TITLE
It seems to work but I still get a [vite] Error when evaluating SSR module.

### ISSUE THREAD

**Issue by bogacg** [paoloricciuti/svelte-client-components#5]
I wanted to give a test run with this preprocessor building a component that basically executes a browser API hence I don't need it SSR side.  
It seems to work, no error in the browser console, however Node console I get this in red:

> [vite] Error when evaluating SSR module /src/routes/DataFromLocalDB.client.svelte

Is this expected? I was thinking this preprocessor doesn't even put `.client.svelte` components into SSR build.  

I don't want t bother you in your vacation, no rush for an answer, thanks.

**Comment by paoloricciuti** [comment]
If you have a reproduction I can take a look

**Comment by bogacg** [comment]
I figured out the problem while preparing a simple reproduction project yet it brings a new question you may have an answer, a better solution than the one I have now.  
Some info about that project:
- Svelte 5
- Component reads previously saved data from IndexedDb and populates a list.
- I'm not using plain IndexedDb but Jake Archibald's package that converts native API into more async one

[GitHub: bogacg/test-client-side-component](https://github.com/bogacg/test-client-side-component)  

The problem code that causes the above mentioned error is  top level `async` call in `<script context="module">` section. Since plain **script** sections don't work for top-level async calls I thought I can use `<script context="module">` to make it work and I wasn't concerned whether it will be shared by all instances of the component or not.  

My current solution is to remove `<script context="module">` and have an IIFE with async call to IndexedDb.  

My new questions (if this isn't the place I can ask them in Discord):  
- What's your take on seeing that error for this preprocessor, makes sense? Should using async code in module context be avoided in the first place? 
- Do you think a better solution than IIFE async for similar cases?
- Since Svelte 5 components are no longer classes, is using `<script context="module">`  have a significant difference than v4?
  - I don't think it does but I didn't dive in Svelte's source code.

Thanks

**Comment by paoloricciuti** [comment]
> What's your take on seeing that error for this preprocessor, makes sense? Should using async code in module context be avoided in the first place?

I will probably need to add this to the list of gotchas...I don't think there's really a way to avoid this with a preprocessor.

> Do you think a better solution than IIFE async for similar cases?

I don't think the IIFE is a bad solution per se, but I would probably just use onMount at that point.

> Since Svelte 5 components are no longer classes, is using <script context="module"> have a significant difference than v4?

It shouldn't: before code was run in the constructor of the class, now in a function. The context module is hoisted above the function in both cases.
